server:
  dev:
    enabled: false
  ha:
    enabled: false
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: null
    accessMode: ReadWriteOnce

  service:
    enabled: true
    type: NodePort
    nodePort: 30022

ui:
  enabled: true
  serviceType: NodePort
  serviceNodePort: 30022

injector:
  enabled: true
