apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: community-dev
data:
  API_URL: "http://backend-service.community-dev.svc.cluster.local:8080"
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  ENABLE_ANALYTICS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: community-dev
data:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  MONGODB_URI: "mongodb://mongodb-service.community-dev.svc.cluster.local:27017/community"
  JWT_SECRET: "${JWT_SECRET}"
  CORS_ORIGIN: "http://frontend-service.community-dev.svc.cluster.local:3000"
  PORT: "8080"
  ENABLE_SWAGGER: "true"
