apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: community-prod
data:
  API_URL: "http://backend-service.community-prod.svc.cluster.local:8080"
  NODE_ENV: "production"
  LOG_LEVEL: "error"
  ENABLE_ANALYTICS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: community-prod
data:
  NODE_ENV: "production"
  LOG_LEVEL: "error"
  MONGODB_URI: "mongodb://mongodb-service.community-prod.svc.cluster.local:27017/community"
  JWT_SECRET: "${JWT_SECRET}"
  CORS_ORIGIN: "http://frontend-service.community-prod.svc.cluster.local:3000"
  PORT: "8080"
  ENABLE_SWAGGER: "false"
