# 공통 설정값
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# 공통 환경 변수 설정
env:
  NODE_ENV: production
  LOG_LEVEL: info

# 공통 이미지 설정
image:
  pullPolicy: IfNotPresent

# 공통 서비스 설정
service:
  type: ClusterIP

# 공통 인그레스 설정
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []

# 공통 자동 확장 설정
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
