name: Backend CI Pipeline

on:
  push:
    branches: [ main, dev, stg, prod ]
  pull_request:
    branches: [ main, dev, stg, prod ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || echo "Linting issues found"
    
    - name: Run tests
      run: npm test -- --coverage
    
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=community-backend
          -Dsonar.organization=devsecops-community
          -Dsonar.sources=src
          -Dsonar.tests=src
          -Dsonar.test.inclusions=**/*.test.js,**/*.test.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.sourceEncoding=UTF-8

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Checkov scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: all
        output_format: cli
        soft_fail: true
    
    - name: Build Docker image
      run: docker build -t harbor.local/community/backend:${{ github.sha }} .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: harbor.local/community/backend:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Generate SBOM
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: harbor.local/community/backend:${{ github.sha }}
        format: 'cyclonedx'
        output: 'sbom.json'
    
    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-sbom
        path: sbom.json

  publish:
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prod')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Harbor Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    
    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.HARBOR_REGISTRY }}/community/backend:${{ github.sha }}
          ${{ secrets.HARBOR_REGISTRY }}/community/backend:${{ env.BRANCH_NAME }}-latest
