expose:
  type: nodePort
  tls:
    enabled: true
    certSource: auto
    auto:
      commonName: "harbor.local"
  nodePort:
    ports:
      http:
        nodePort: 30002
      https:
        nodePort: 30003

externalURL: https://harbor.local:30003

harborAdminPassword: "Harbor12345"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 5Gi
    chartmuseum:
      size: 1Gi
    jobservice:
      size: 1Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
    trivy:
      size: 1Gi

trivy:
  enabled: true

notary:
  enabled: false

database:
  internal:
    password: "Harbor12345"

core:
  replicas: 1
  xsrfKey: "uBFDfEbKCZvUFZsSiPIljRPEAevjwGJG"

jobservice:
  replicas: 1

registry:
  replicas: 1

portal:
  replicas: 1

chartmuseum:
  enabled: true
  replicas: 1

log:
  level: info
